#!/bin/sh

apt-get update
apt-get install -y make busybox python-pip
pip install https://github.com/larsks/dockerize/archive/master.zip
dockerize -t eyigitoglu/raspberrypitest \
   --add-file index.html /www/ \
   --add-file pi_armed_with_docker.jpg /www/ \
   --entry '/bin/busybox' \
   --cmd 'httpd -f -p 80 -h /www' \
   /bin/busybox


docker tag -f eyigitoglu/raspberrypitest eyigitoglu/raspberrypitest:latest
docker build -t eyigitoglu/raspberrypitest .
