#!/bin/sh

apt-get update

apt-get --assume-yes install build-essential expect
set cmd "ssh -l pirate 9.1.75.112 -O 'docker ps' "
/usr/bin/expect <<EOD
spawn $cmd
expect "pirate@9.1.75.112's password:"
send "hypriot \n"
expect eof
EOD

# sshpass -p "hypriot" ssh  pirate@9.1.75.112 "docker run -d -p 80:80 eyigitoglu/raspberrypitest ."


# spawn ssh pirate@9.1.75.112 "docker stop $(docker ps -q --filter ancestor=eyigitoglu/raspberrypitest)"
